<?php
	define('DG_DEBUG_MODE', TRUE);
	define('DG_REAL_HOST', 'http://playground.dev/projects/wgc/');
	define('DG_REAL_HOST_NAME', 'World Generator Calculator');
	define('DG_SQL_MYSQL_DEFAULT', 'localhost, root, D@rk+Gr@y, wgc, 3306');
	
	define('DG_AJAX_ID', 'ajax');
	define('DG_AJAX_VALUE', 1);
	define('DG_AJAX_SCOPE', 'post');
	
	function AbstractedcControlEngine($obj){ /* Coming Soon */ }
?>